/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallRouteImport } from './routes/call'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PersonalitiesRouteImport } from './routes/personalities'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as VoicesRouteImport } from './routes/voices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalitiesRoute = PersonalitiesRouteImport.update({
  id: '/personalities',
  path: '/personalities',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VoicesRoute = VoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/permissions': typeof PermissionsRoute
  '/personalities': typeof PersonalitiesRoute
  '/profile': typeof ProfileRoute
  '/voices': typeof VoicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/permissions': typeof PermissionsRoute
  '/personalities': typeof PersonalitiesRoute
  '/profile': typeof ProfileRoute
  '/voices': typeof VoicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/permissions': typeof PermissionsRoute
  '/personalities': typeof PersonalitiesRoute
  '/profile': typeof ProfileRoute
  '/voices': typeof VoicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call'
    | '/chat'
    | '/dashboard'
    | '/history'
    | '/permissions'
    | '/personalities'
    | '/profile'
    | '/voices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call'
    | '/chat'
    | '/dashboard'
    | '/history'
    | '/permissions'
    | '/personalities'
    | '/profile'
    | '/voices'
  id:
    | '__root__'
    | '/'
    | '/call'
    | '/chat'
    | '/dashboard'
    | '/history'
    | '/permissions'
    | '/personalities'
    | '/profile'
    | '/voices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallRoute: typeof CallRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  PermissionsRoute: typeof PermissionsRoute
  PersonalitiesRoute: typeof PersonalitiesRoute
  ProfileRoute: typeof ProfileRoute
  VoicesRoute: typeof VoicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalities': {
      id: '/personalities'
      path: '/personalities'
      fullPath: '/personalities'
      preLoaderRoute: typeof PersonalitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voices': {
      id: '/voices'
      path: '/voices'
      fullPath: '/voices'
      preLoaderRoute: typeof VoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallRoute: CallRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  PermissionsRoute: PermissionsRoute,
  PersonalitiesRoute: PersonalitiesRoute,
  ProfileRoute: ProfileRoute,
  VoicesRoute: VoicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
